- name: Check if CNI plugins are already installed
  ansible.builtin.find:
    paths: "/opt/cni/bin"
    patterns: "bridge"
  register: minikube_cni_installed

- name: Download CNI plugins tarball
  ansible.builtin.get_url:
    url: "https://github.com/containernetworking/plugins/releases/download/v1.6.2/cni-plugins-linux-amd64-v1.6.2.tgz"
    dest: "/tmp/cni-plugins-linux-amd64-v1.6.2.tgz"
    mode: '0644'
  when: minikube_cni_installed.matched == 0

- name: Create CNI installation directory
  ansible.builtin.file:
    path: "/opt/cni/bin"
    state: directory
    mode: '0755'
  when: minikube_cni_installed.matched == 0

- name: Extract CNI plugins
  ansible.builtin.unarchive:
    src: "/tmp/cni-plugins-linux-amd64-v1.6.2.tgz"
    dest: "/opt/cni/bin"
  when: minikube_cni_installed.matched == 0

- name: Remove CNI tarball
  ansible.builtin.file:
    path: "/tmp/cni-plugins-linux-amd64-v1.6.2.tgz"
    state: absent
