- name: Ensure dnf-plugins-core is installed (provides config-manager)
  ansible.builtin.dnf:
    name: dnf-plugins-core
    state: present

- name: Add Docker repository using dnf config-manager
  ansible.builtin.command:
    cmd: dnf-3 config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
    creates: /etc/yum.repos.d/docker-ce.repo
  become: true

- name: Install Docker
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Add user to Docker group
  ansible.builtin.user:
    name: "{{ ansible_env.SUDO_USER }}"
    groups: docker
    append: true

- name: Ensure Docker service is enabled and running
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started

- name: Ensure Docker socket permissions
  ansible.builtin.file:
    path: /var/run/docker.sock
    owner: root
    group: docker
    mode: '0760'
  notify: Restart Docker
