- name: Ensure dnf-plugins-core is installed (provides config-manager)
  ansible.builtin.dnf:
    name: dnf-plugins-core
    state: present

- name: Add Docker repository using yum_repository
  ansible.builtin.yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    baseurl: "https://download.docker.com/linux/fedora/docker-ce.repo"
    gpgcheck: true
    gpgkey: "https://download.docker.com/linux/fedora/gpg"
    enabled: true
    state: present

- name: Install Docker
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Add user to Docker group
  ansible.builtin.user:
    name: "{{ ansible_env.SUDO_USER }}"
    groups: docker
    append: true

- name: Ensure Docker socket permissions
  ansible.builtin.file:
    path: /var/run/docker.sock
    owner: root
    group: docker
    mode: '0760'
  notify: Restart Docker
