- name: Check if minikube is already installed
  ansible.builtin.command:
    cmd: "minikube --version"
  register: cri_dockerd_installed
  changed_when: false
  ignore_errors: true

- name: Download and install Minikube
  ansible.builtin.get_url:
    url: "https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-amd64"
    dest: "/usr/local/bin/minikube"
    mode: "0755"
  when: minikube_installed.rc != 0

- name: Create systemd service file for Minikube
  ansible.builtin.copy:
    dest: /etc/systemd/system/minikube.service
    content: |
      [Unit]
      Description=Kickoff Minikube Cluster
      After=docker.service

      [Service]
      Type=oneshot
      ExecStart=/usr/local/bin/minikube start --driver=none
      RemainAfterExit=true
      ExecStop=/usr/local/bin/minikube stop
      StandardOutput=journal
      User=root
      Group=root

      [Install]
      WantedBy=multi-user.target
    mode: "0644"

- name: Reload systemd to read new service
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable Minikube service to start on boot
  ansible.builtin.systemd:
    name: minikube
    enabled: true

- name: Start Minikube service
  ansible.builtin.systemd:
    name: minikube
    state: started

- name: Ensure filesystem access (did I tell that you that this should run on a dedicated machine?)
  ansible.builtin.sysctl:
    name: fs.protected_regular
    value: '0'
    state: present
    reload: true
