- name: Add HashiCorp repository
  ansible.builtin.yum_repository:
    name: hashicorp
    description: HashiCorp Stable - Fedora
    baseurl: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
    gpgcheck: true
    repo_gpgcheck: true
    enabled: true
    gpgkey: https://rpm.releases.hashicorp.com/gpg

- name: Install Terraform
  ansible.builtin.dnf:
    name:
      - terraform
    state: present

- name: Create tfstate directory
  ansible.builtin.file:
    path: /var/lib/plateng
    state: directory
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: "0755"
    recurse: true

- name: Ensure home root exists
  ansible.builtin.file:
    path: /home/root/
    state: directory
    mode: '0755'
    become: true

- name: Create .terraformrc file with plugin_cache_dir
  ansible.builtin.copy:
    dest: "/home/{{ ansible_env.USER }}/.terraformrc"
    content: |
      plugin_cache_dir = "~/"
    owner: "root"
    group: "root"
    mode: '0644'
    become: true
  when: ansible_env.USER is defined
