- name: Ensure the auth directory exists
  ansible.builtin.file:
    path: "~/auth"
    state: directory
    mode: '0700'

- name: Generate htpasswd file
  ansible.builtin.command:
    cmd: "htpasswd -Bbn {{ registry_user }} {{ registry_password }}"
  register: htpasswd_output
  changed_when: true
  no_log: true

- name: Save htpasswd file
  ansible.builtin.copy:
    content: "{{ htpasswd_output.stdout }}"
    dest: "{{ htpasswd_file }}"
    mode: '0600'
