- name: Add github GPG key
  ansible.builtin.get_url:
    url:  "https://cli.github.com/packages/githubcli-archive-keyring.gpg"
    dest: "/etc/apt/keyrings/githubcli-archive-keyring.gpg"
    mode: '0644'


- name: Add GitHub CLI APT repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://cli.github.com/packages stable main"
    state: present
    filename: github-cli


- name: Install GitHub CLI
  ansible.builtin.apt:
    name: gh
    state: present
