- name: Add GitHub CLI repository GPG key
  ansible.builtin.apt_key:
    url: https://cli.github.com/packages/githubcli.asc
    state: present
  become: true

- name: Add GitHub CLI APT repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://cli.github.com/packages stable main"
    state: present
    update_cache: yes
  become: true

- name: Install GitHub CLI
  ansible.builtin.apt:
    name: gh
    state: present
  become: true