---
apiVersion: marketplace.kratix.io/v1alpha1
kind: Runtime
metadata:
  name: llama-proxy
  namespace: default
spec:
  lifecycle: dev
  image: 192.168.49.2:30080/llama-proxy:1019fdf9e595b1e70f3b781cf63ac9b04826aa1844bd019b06f0234a99f3167a
  servicePort: 80
  replicas: 1
  applicationEnv:
    - name: hello
      value: from-env
