apiVersion: marketplace.kratix.io/v1alpha1
kind: Runtime
metadata:
  name: multiply
  namespace: default
spec:
  lifecycle: dev
  image: localhost:30080/multiply:896e9de4fe39abd5dda854029777a67af0b618fe1df8c3049893441a752eb6fa
  servicePort: 80
  replicas: 1
  applicationEnv:
  - name: hello
    value: from-env