apiVersion: marketplace.kratix.io/v1alpha1
kind: Runtime
metadata:
  name: multiply
  namespace: default
spec:
  lifecycle: dev
  image: registry.docker-registry.svc.cluster.local:5000/multiply:82c7b2782ac0f381529f33629bd8a2db225a2246f65a198f46f21a983a8cb625
  servicePort: 80
  replicas: 1
  applicationEnv:
  - name: hello
    value: from-env