---
apiVersion: marketplace.kratix.io/v1alpha1
kind: Runtime
metadata:
  name: multiply
  namespace: default
spec:
  lifecycle: dev
  image: 192.168.49.2:30080/multiply:ddd041993da688306dc097371d6218927fbb39dd14780faae9c263ac5bcdcdf4
  servicePort: 80
  replicas: 1
  applicationEnv:
    - name: hello
      value: from-env
