apiVersion: marketplace.kratix.io/v1alpha1
kind: Runtime
metadata:
  name: multiply
  namespace: default
spec:
  lifecycle: dev
  image: 192.168.49.2:30080/multiply:148166812f0f391baef62dff1d0ed1287c8fb35ebd2c76850dce36803942687d
  servicePort: 80
  replicas: 1
  applicationEnv:
  - name: hello
    value: from-env