apiVersion: marketplace.kratix.io/v1alpha1
kind: Runtime
metadata:
  name: ping-llama
  namespace: default
spec:
  lifecycle: dev
  image: 192.168.49.2:30080/ping-llama:cef3951155ec951cfafdfa8546e6e8377fcb1fb0ebe5d3f4f9788c8822622b25
  servicePort: 80
  replicas: 1
  applicationEnv:
  - name: hello
    value: from-env