apiVersion: marketplace.kratix.io/v1alpha1
kind: Runtime
metadata:
  name: ping-llama
  namespace: default
spec:
  lifecycle: dev
  image: 192.168.49.2:30080/ping-llama:e399dd2b6521017cca7b4c3e0296c0d2a6e82d71eaabd41cc8d9d6c4a70c8a96
  servicePort: 80
  replicas: 1
  applicationEnv:
  - name: hello
    value: from-env