apiVersion: marketplace.kratix.io/v1alpha1
kind: Runtime
metadata:
  name: test
  namespace: default
spec:
  lifecycle: dev
  image: localhost:30080/test:70991446aae0c7718a78c3f3273fc6cd9cc4ad1c21b72c487daf16efd1b4f609
  servicePort: 80
  replicas: 1
  applicationEnv:
  - name: hello
    value: from-env