apiVersion: marketplace.kratix.io/v1alpha1
kind: Runtime
metadata:
  name: time-now
  namespace: default
spec:
  lifecycle: dev
  image: localhost:30080/time_now:89ccf8d42179d37a5533590028b8cb3336184bb8b271dc15565d00d5e6e92b44
  servicePort: 80
  replicas: 1
  applicationEnv:
  - name: hello
    value: from-env