- name: Install Conntrack
  ansible.builtin.apt:
    name:
      - conntrack
    state: present

- name: Download crictl tarball
  ansible.builtin.get_url:
    url: "https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.32.0/crictl-v1.32.0-linux-amd64.tar.gz"
    dest: "/tmp/crictl-v1.32.0-linux-amd64.tar.gz"
    mode: '0644'

- name: Extract crictl tarball to /usr/local/bin
  ansible.builtin.unarchive:
    src: "/tmp/crictl-v1.32.0-linux-amd64.tar.gz"
    dest: "/usr/local/bin"

- name: Remove crictl tarball
  ansible.builtin.file:
    path: "/tmp/crictl-v1.32.0-linux-amd64.tar.gz"
    state: absent

- name: Download cri-dockerd tarball
  ansible.builtin.get_url:
    url: "https://github.com/Mirantis/cri-dockerd/releases/download/v0.3.16/cri-dockerd-0.3.16.amd64.tgz"
    dest: "/tmp/cri-dockerd-0.3.16.amd64.tgz"
    mode: '0644'

- name: Extract cri-dockerd tarball to /usr/local/bin
  ansible.builtin.unarchive:
    src: "/tmp/cri-dockerd-0.3.16.amd64.tgz"
    dest: "/usr/local/bin"

- name: Remove cri-dockerd tarball
  ansible.builtin.file:
    path: "/tmp/cri-dockerd-0.3.16.amd64.tgz"
    state: absent
