- name: Add Kubectl GPG key
  ansible.builtin.shell:
    cmd: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key | gpg --dearmor | sudo tee /etc/apt/keyrings/kubernetes-apt-keyring.gpg > /dev/null
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubectl repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg]
       https://pkgs.k8s.io/core:/stable:/v1.32/deb/
       /
    state: present
    filename: kubernetes

- name: Install Kubectl
  ansible.builtin.apt:
    name:
      - kubectl
    state: present
