- name: Configure docker
  ansible.builtin.include_tasks: docker.yaml

- name: Configure unzip
  ansible.builtin.include_tasks: unzip.yaml

- name: Configure kubectl
  ansible.builtin.include_tasks: kubectl.yaml

- name: Configure cri-dockerd
  ansible.builtin.include_tasks: crictl.yaml

- name: Configure CNI plugin
  ansible.builtin.include_tasks: cni-plugins.yaml

- name: Configure minikube
  ansible.builtin.include_tasks: minikube.yaml

- name: Configure nodejs
  ansible.builtin.include_tasks: nodejs.yaml

- name: Configure terraform
  ansible.builtin.include_tasks: terraform.yaml
