- name: Add Terraform GPG key
  ansible.builtin.get_url:
    url: "https://apt.releases.hashicorp.com/gpg"
    dest: "/usr/share/keyrings/hashicorp-archive-keyring.gpg"
    mode: '0644'

- name: Add Terraform repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg]
      https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
    state: present
    filename: hashicorp

- name: Install Terraform
  ansible.builtin.apt:
    name:
      - terraform
    state: present

- name: Create tfstate directory
  ansible.builtin.file:
    path: /var/lib/plateng
    state: directory
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: "0755"