- name: Install essential development tools and libraries
  ansible.builtin.dnf:
    name:
      - "@c-development"
      - "@development-tools"
      - cmake
    state: present

- name: Add Nvidia repository using dnf config-manager
  ansible.builtin.command:
    cmd: dnf-3 config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/fedora41/x86_64/cuda-fedora41.repo
    creates: /etc/yum.repos.d/docker-ce.repo
  become: true