- name: Setup DevOps Environment
  hosts: local
  become: true
  roles:
    - role: minikube
    
    - role: docker-registry
      vars: 
        registry_user: "{{ registry_user }}"
        registry_password: "{{ registry_password }}"

