name: Build docker image

on:
  workflow_dispatch:
  push:
    paths:
      - 'generated_dockerfiles'
      - '.github/workflows/build_docker_image.yaml'
      - 'workflow_scripts/build_docker_image'
  pull_request:

jobs: 
  build-image:
    runs-on: self-hosted

    steps:
      - name: force clean Repository
        run: sudo rm -rf ${{ github.workspace }}/terraform

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Run Dockerfile generation script
        run: | 
          python workflow_scripts/generate_dockerfiles/generate_dockerfiles.py \
           --dockerfiles-dir generated_dockerfiles \
           --docker-registry ${{ secrets.DOCKER_REGISTRY }}
        env:
          DOCKER_HOST: "localhost:30080"
          DOCKER_USERNAME: ${{ secrets.REGISTRY_USER }}
          DOCKER_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
