name: Configure host

on:
  workflow_dispatch:
  push:
    paths:
      - 'ansible/**'
  pull_request:

jobs:
  ansible:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook
        run: |
          sudo ansible-playbook -i ansible/inventory ansible/host.yaml

      - name: force clean Repository
        run: sudo rm -rf ${{ github.workspace }}/terraform
