name: Configure host

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    paths:
      - 'ansible/**'
  pull_request:

jobs:
  ansible:
    runs-on: self-hosted

    steps:
      - name: force clean Repository
        run: sudo rm -rf ${{ github.workspace }}/terraform

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible
        shell: bash
        run: |
          sudo dnf install -y ansible

      - name: Run Ansible Playbook
        run: |
          sudo ansible-playbook -i ansible/inventory ansible/host.yaml \
          --extra-vars "registry_user=${{ secrets.REGISTRY_USER }} registry_password=${{ secrets.REGISTRY_PASSWORD }}"

      - name: force clean Repository
        run: sudo rm -rf ${{ github.workspace }}/terraform
