name: Deploy

on:
  workflow_dispatch:
  push:
    paths:
      - 'terraform/**'
  pull_request:

jobs:
  terraform:
    runs-on: self-hosted

    steps:
      - name: force clean Repository
        run: sudo rm -rf ${{ github.workspace }}/terraform

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Initialize Terraform
        run: sudo terraform -chdir=terraform init

      - name: Debug Environment Variables
        run: |
          echo "TF_VAR_harbor_url=${TF_VAR_harbor_url_invalid}"
        env:
          TF_VAR_harbor_url: ${{ secrets.HARBOR_URL }}

      - name: Apply Terraform
        env:
          TF_VAR_harbor_url: ${{ secrets.HARBOR_URL }}
          TF_VAR_harbor_username: ${{ secrets.HARBOR_USERNAME }}
          TF_VAR_harbor_password: ${{ secrets.HARBOR_PASSWORD }}
        run: sudo terraform -chdir=terraform apply -auto-approve

      - name: force clean Repository
        run: sudo rm -rf ${{ github.workspace }}/terraform