name: Deploy Kratix

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/deploy_kratix.yaml'
  pull_request:

jobs: 
  deploy-kratix:
    runs-on: self-hosted

    steps:
      - name: force clean Repository
        run: sudo rm -rf ${{ github.workspace }}/terraform

      - name: Deploy cert manager
        run: |
         sudo kubectl apply \
         --filename https://github.com/cert-manager/cert-manager/releases/download/v1.15.0/cert-manager.yaml

      - name: Wait for 10s deployment to finish
        run: sleep 10 

      - name: Install Kratix
        run: | 
          sudo kubectl apply \
          --filename https://github.com/syntasso/kratix/releases/latest/download/install-all-in-one.yaml

      - name: Wait for 10s deployment to finish
        run: sleep 10 

      - name: Configure Kratix
        run: | 
          sudo kubectl apply \
          --filename https://github.com/syntasso/kratix/releases/latest/download/config-all-in-one.yaml

