name: Deploy

on:
  push:
    branches:
      - main
      - initial-commit

jobs:
  terraform:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Install Ansible
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook
        run: |
          sudo ansible-playbook -i ansible/inventory ansible/host.yaml

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Initialize Terraform
        run: terraform -chdir=terraform init

      - name: Apply Terraform
        run: terraform -chdir=terraform apply -auto-approve
