name: Deploy

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    paths:
      - 'terraform/**'
  pull_request:

jobs:
  terraform:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Initialize Terraform
        run: terraform -chdir=terraform init

      - name: Apply Terraform
        run: >-
          terraform -chdir=terraform apply -auto-approve 

      - name: force clean Repository
        run: sudo rm -rf ${{ github.workspace }}/terraform