name: Deploy Kratix

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/deploy_kratix.yaml'
  pull_request:

jobs: 
  deploy-kratix:
    runs-on: self-hosted

    steps:
      - name: Deploy cert manager
        run: |
         kubectl apply \
           --filename https://github.com/cert-manager/cert-manager/releases/download/v1.15.0/cert-manager.yaml
         sudo kubectl wait --namespace cert-manager \
          --for=condition=Available deployments \
          --all \
          --timeout=300s

      - name: Install Kratix
        run: | 
          kubectl apply \
           --filename https://github.com/syntasso/kratix/releases/latest/download/install-all-in-one.yaml
           sudo kubectl wait --namespace kratix-platform-system \
            --for=condition=Available deployments \
            --all \
            --timeout=300s

      - name: Configure Kratix
        run: | 
          kubectl apply \
            --filename https://github.com/syntasso/kratix/releases/latest/download/config-all-in-one.yaml
          kubectl wait --namespace kratix-platform-system \
            --for=condition=Available deployments \
            --all \
            --timeout=300s
          
      - name: Instal Runtime marketplace module
        run: | 
          kubectl apply \
            --filename https://raw.githubusercontent.com/syntasso/kratix-marketplace/main/runtime/promise.yaml
          kubectl wait \
          --for=condition=Available deployments \
          --all \
          --timeout 300s

