name: Deploy

on:
  workflow_dispatch:
  push:
    paths:
      - 'terraform/**'
  pull_request:

jobs:
  terraform:
    runs-on: self-hosted

    steps:
      - name: force clean Repository
        run: sudo rm -rf ${{ github.workspace }}/terraform

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Initialize Terraform
        run: sudo terraform -chdir=terraform init

      - name: Apply Terraform
        run: >-
          sudo terraform -chdir=terraform apply -auto-approve 
          -var "harbor_url=${{ secrets.HARBOR_URL}}"
          -var "harbor_username=${{ secrets.HARBOR_USERNAME}}"
          -var "harbor_password=${{ secrets.HARBOR_PASSWORD}}"


      - name: force clean Repository
        run: sudo rm -rf ${{ github.workspace }}/terraform