name: Generate Dockerfiles

on:
  push:
    paths:
      - "webservices/**.py"
  workflow_dispatch: # Allows manual triggering

jobs:
  generate-dockerfiles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install ruff

      - name: Run linter (ruff)
        run: ruff check webservices/ workflow_scripts/

      - name: Run Dockerfile generation script
        run: python workflow_scripts/generate_dockerfiles.py

      - name: Commit and Push Changes
        id: commit_and_push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          TIMESTAMP="$(date +'%Y%m%d%H%M%S')"
          BRANCH_NAME="generate-dockerfiles-$TIMESTAMP"
          git checkout -b $BRANCH_NAME
          git add generated_dockerfiles/
          git commit -m "Auto-generate Dockerfiles for new webservices"
          git push origin $BRANCH_NAME
          echo echo "branch_name"="$BRANCH_NAME" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: $branch_name
          title: "Auto-generate Dockerfiles for new webservices"
          body: "This PR adds Dockerfiles for newly detected Python web services."
          base: main
          token: ${{ secrets.GITHUB_TOKEN }}