name: Ansible files & Deployment 

on:
  push:
    paths:
      - 'ansible/**'
  pull_request:
    paths:
      - 'ansible/**'

jobs:
  ansible-lint:
    runs-on: self-hosted
    uses: ansible/ansible-content-actions/.github/workflows/ansible_lint.yaml@main
    with:
      args: '-p ansible'