name: Ansible lint

on:
  push:
    workflow_dispatch:
    paths:
      - 'ansible/**'
    branches:
      - main
      - initial-commit
  pull_request:
    paths:
      - 'ansible/**'

    

jobs:
  ansible:

    runs-on: self-hosted 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Ensure python is intalled
        run: sudo apt install python3-pip -y

      - name: Ensure ansible is intalled
        run: sudo pip3 install ansible-dev-tools

      - name: Run Ansible Lint
        run: ansible-lint ansible/