name: Ansible lint

on:
  workflow_dispatch:
  push:
    paths:
      - 'ansible/**'
      - .github/workflows/lint_ansible.yaml
  pull_request:

jobs:
  ansible:

    runs-on: self-hosted 

    steps:
      - name: force clean Repository
        run: sudo rm -rf ${{ github.workspace }}/terraform

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Ensure ansible is intalled
        run: pip install ansible-dev-tools

      - name: Run Ansible Lint
        run: ansible-lint ansible/

      - name: force clean Repository
        run: sudo rm -rf ${{ github.workspace }}/terraform
 