name: Python lint

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    paths:
      - 'webservices/**'
      - 'workflow_scripts/**'
      - '.github/workflows/lint_python.yaml'
  pull_request:

jobs:
  python-lint:

    runs-on: self-hosted 

    steps:
      - name: force clean Repository
        run: sudo rm -rf ${{ github.workspace }}/terraform

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        run: sudo dnf install python3 python3-pip -y

      - name: Ensure ruff is intalled
        run: pip install ruff

      - name: Run ruff
        run: ruff check webservices workflow_scripts