name: Ansible files & Deployment 

on:
  push:
    paths:
      - 'ansible/**'
  pull_request:
    paths:
      - 'ansible/**'

jobs:
    runs-on: self-hosted 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Ansible Lint
        run: ansible-lint ansible/