name: Ansible lint

on:
  push:
    paths:
      - 'ansible/**'
  pull_request:
    paths:
      - 'ansible/**'

jobs:
  ansible:

    runs-on: self-hosted 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Ensure python is intalled
        run: sudo apt install python3 -y

      - name: Ensure ansible-lint is intalled
        run: pip install ansible-lint

      - name: Run Ansible Lint
        run: ansible-lint ansible/