name: Ansible lint

on:
  workflow_dispatch:
  push:
    paths:
      - 'webservices/*'
      - 'workflow_scripts/*'
      - '.github/workflows/lint_python.yaml'
  pull_request:

jobs:
  ansible:

    runs-on: self-hosted 

    steps:
      - name: force clean Repository
        run: sudo rm -rf ${{ github.workspace }}/terraform

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Ensure ruff is intalled
        run: sudo pip install ruff

      - name: Run ruff
        run: ruff check webservices workflow_scripts